modLoader="javafml"
loaderVersion="[43,)"

license="MIT"
issueTrackerURL="https://github.com/thraaawn/libnonymous/issues"

[[mods]]
modId="libnonymous"
version="${file.jarVersion}"
displayName="Libnonymous"
displayURL="https://github.com/thraaawn/libnonymous"
logoFile="libnonymous.png"
authors="Davenonymous"
description='''
Library mod for mods by Davenonymous.
Currently used by:
- Bonsai Trees
- SlimeClicker (unreleased)
- RiddleChests (unreleased)
'''

[[dependencies.libnonymous]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.libnonymous]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"